---
title: "AFCA_analysis"
description: "Analysis of the afca dataset across different cell types and ages using 
              Seurat for MAST based differential expression analysis with the sample (individual fly) 
              as a latent variable. Followed by Wilcoxon rank sum test for solely enterocyte types."
output: html_document
date: "2025-04-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "D:/projects/ageing_flies")
```

Load the libraries 
```{r}
library(SeuratData)
library(Seurat)
library(zellkonverter)
library(MAST)
library(dplyr)
library(fs)
library(stats)
library(devtools)
library(utils)
```

Set the file and folder info
```{r}
# Set the Results path
date <- format(Sys.Date(), "%Y%m%d")
results_path <- fs::path("Results/age_scdgea", date)
if (!dir.exists(results_path)) {
  dir.create(results_path, recursive = TRUE)
}

# Set output file path
results_file <- file.path(results_path, "entero_markers.csv")
# remove file if it exists
if (file.exists(results_file)) {
  file.remove(results_file)
}
```


```{r}
# Get the file name without the extension
filepath <- fs::path("Data/entero_expr_set.h5ad")
file_name <- path_file(filepath)
print(file_name)
ct_name <- path_ext_remove(file_name)
print(ct_name)


# Convert the Anndata to Seurat

suppressWarnings({
  ad <- readH5AD(as.character(filepath))
  adata_Seurat <- as.Seurat(ad, counts = "X", data = NULL)
  })
rm(ad)

# Convert the variables 
adata_Seurat$age <- as.factor(adata_Seurat$age)
adata_Seurat$sex_age <- as.factor(adata_Seurat$sex_age)
adata_Seurat$afca_annotation <- as.factor(adata_Seurat$afca_annotation)

# Define groups 
young_group <- "5" 
all_groups <- unique(adata_Seurat$age)
other_groups <- setdiff(all_groups, young_group)

# Get the age groups in the data 
groups_present <- unique(adata_Seurat$age)

# Run the differential expression analysis
if (young_group %in% groups_present) {
  for (grp in other_groups) {
    if (grp %in% groups_present) {
      cat(paste("  Running DGEA for:", young_group, "vs", grp, "\n"))
      markers <- FindMarkers(adata_Seurat,
                             ident.1 = young_group,
                             ident.2 = grp,
                             group.by = "age",
                             test.use = "MAST",
                             latent.vars = "batch"
                             )

      # add cell type and comparison columns
      markers$cell_type <- ct_name
      markers$comparison <- paste(young_group, "vs", grp)
      markers$gene <- rownames(markers)

      # rename the BF corretion
      markers <- markers %>% rename(
        p_val_BF = p_val_adj
        )
      # perform the BH correction
      markers$p_val_adj <- p.adjust(markers$p_val, method = "BH")

      # Write to CSV file (with header if first write)
      write.table(markers, results_file,
                  sep = ",",
                  row.names = FALSE,
                  col.names = !file.exists(results_file),
                  append = file.exists(results_file))
      
      Cat(paste("  Finished DGEA for:", young_group, "vs", grp, "\n"))
    }
  }
}
cat("\t\t Finished DGEA for all groups \n")

  

```












